### List all messages
GET http://localhost:3000/messages

### Post message
POST http://localhost:3000/messages
content-type: application/json

{
    "content": "hi there! 3"
}

### Get message by ID
GET http://localhost:3000/messages/531